version: "3.8"

services:
  wordpress:
    env_file:
      - ./.env
    container_name: WP__${PROJECT_NAME}
    image: ghcr.io/hansanghyeon/wordpress-redis:php8.0-apache-redis
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis */
        define('WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_HOST', 'redis'));
        define('WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', 6379));
    volumes:
      - ./.wordpress:/var/www/html
      - ./Theme:/var/www/html/wp-content/themes/sage
      - ./backup:/var/www/html/wp-content/ai1wm-backups
  db:
    image: mariadb
    container_name: DB__work
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: wp
      MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    container_name: DB__adminer
    restart: always
    ports:
      - 3306:8080
  redis:
    container_name: DB__redis
    image: redis:latest
    volumes:
      - redis:/data

volumes:
  redis:
