#####################################
# swarm에서 작동하는 docker-compose
#####################################

version: "3.8"

########################### SERVICES
services:
  wordpress:
    image: wordpress:php8.0
    environment:
      WORDPRESS_DB_HOST: DB_workdb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./.wordpress:/var/www/html
      - ./Theme:/var/www/html/wp-content/themes/sage
      - ./backup:/var/www/html/wp-content/ai1wm-backups
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        - traefik.http.routers.work-202108__${PROJECT_NAME}.entrypoints=websecure
        - traefik.http.routers.work-202108__${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.demo.hyeon.pro`)
        - traefik.http.routers.work-202108__${PROJECT_NAME}.tls.certresolver=leresolver
        - traefik.http.services.work-202108__${PROJECT_NAME}.loadbalancer.server.port=80

########################### NETWORKS
networks:
  default:
    external:
      name: DB_work
