name: 🚛 매뉴얼 배포
on:
  release:
    types: [published]
    paths:
      - "Theme/**/*"
  push:
    branches: [main, develop]
    paths:
      - "Theme/**/*"
  workflow_dispatch:

jobs:
  source:
    if: ${{ github.event.repository.owner.name == 'peterosea' }}
    runs-on: ubuntu-latest
    name: 📮 Github 소스코드로 업데이트 `git pull origin main`
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DEPLOYSERVER_KEY }}
          host: ${{ secrets.DEPLOYSERVER_HOST }}
          username: ${{ secrets.DEPLOYSERVER_USERNAME }}
          port: ${{ secrets.DEPLOYSERVER_PORT }}
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git fetch origin
            git checkout main
            git branch | grep 'release/*' | xargs git branch -D
            git pull origin main

  build:
    if: ${{ github.event.repository.owner.name == 'peterosea' }}
    runs-on: ubuntu-latest
    name: 🗳 Theme source build & rsync
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        working-directory: ${{ env.working-directory }}
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ env.working-directory }}/node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 🏗 setup-node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        if: ${{steps.yarn-cache.outputs.cache-hit}} != 'true'
        working-directory: ${{ env.working-directory }}
        run: |
          cd ${{ secrets.SRC }}
          yarn install
      - name: 🔨 yarn install & build
        run: |
          cd ${{ secrets.SRC }}
          yarn build:production

      - name: 📂 Sync files to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOYSERVER_KEY }}
          SERVER_PORT: ${{ secrets.DEPLOYSERVER_RSYNC_PORT }}
          SERVER_IP: ${{ secrets.DEPLOYSERVER_HOST }}
          USERNAME: ${{ secrets.DEPLOYSERVER_USERNAME }}
          FOLDER: "./${{ secrets.SRC }}/public"
          ARGS: "-rltgoDzvO --ignore-times"
          SERVER_DESTINATION: "${{ secrets.PROJECT_DIR }}/${{ secrets.SRC }}"
