name: 🚛 static code deploy
on:
  push:
    branches: [release/*]
    paths:
      - "Theme/resources/views/**/*"
      - "Theme/resources/fonts/**/*"
      - "Theme/resources/images/**/*"
      - "Theme/resources/video/**/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  source:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.name == 'peterosea' }}
    name: 📮 Github 소스코드로 업데이트 `git checkout release/* && git pull origin release/*`
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DEPLOYSERVER_KEY }}
          host: ${{ secrets.DEPLOYSERVER_HOST }}
          username: ${{ secrets.DEPLOYSERVER_USERNAME }}
          port: ${{ secrets.DEPLOYSERVER_PORT }}
          script: |
            cd www
            git fetch origin
            git pull origin ${GITHUB_REF##*/}
            git checkout ${GITHUB_REF##*/}
